
`███████╗ █████╗ ██╗  ████████╗    ████████╗ ██████╗  █████╗ ███████╗████████╗███████╗██████╗`
`██╔════╝██╔══██╗██║  ╚══██╔══╝    ╚══██╔══╝██╔═══██╗██╔══██╗██╔════╝╚══██╔══╝██╔════╝██╔══██╗`
`███████╗███████║██║     ██║          ██║   ██║   ██║███████║███████╗   ██║   █████╗  ██████╔`
`╚════██║██╔══██║██║     ██║          ██║   ██║   ██║██╔══██║╚════██║   ██║   ██╔══╝  ██╔══██╗`
`███████║██║  ██║███████╗██║          ██║   ╚██████╔╝██║  ██║███████║   ██║   ███████╗██║  ██║`
`╚══════╝╚═╝  ╚═╝╚══════╝╚═╝          ╚═╝    ╚═════╝ ╚═╝  ╚═╝╚══════╝   ╚═╝   ╚══════╝╚═╝  ╚═╝`

`///////////////////////////////////////////////////`
`// Salt Toaster: An ultimate test suite for Salt //`
`///////////////////////////////////////////////////`

// settings:
:page-layout: base
:idprefix:
:idseparator: -
:source-highlighter: pygments
:source-language: python
ifndef::env-github[:icons: font]
ifdef::env-github[]
:status:
:outfilesuffix: .adoc
:caution-caption: :fire:
:important-caption: :exclamation:
:note-caption: :paperclip:
:tip-caption: :bulb:
:warning-caption: :warning:
endif::[]

image:https://api.travis-ci.org/openSUSE/salt-toaster.svg?branch=master[Build Status, link=https://travis-ci.org/openSUSE/salt-toaster]

== Description

This is a tool used to test https://github.com/saltstack/salt/[salt]
It uses pytest and containers to do so.
The tests are separated in 3 groups:
 - upstream integration tests
 - upstream unit tests
 - suse integration tests

There are 3 predefined flavors of salt packages plus a `devel` flavor.
The predefined flavors are packages served from OBS:

 - https://build.opensuse.org/package/show/systemsmanagement:saltstack:products/salt[products], the flavor for released packages
 - https://build.opensuse.org/package/show/systemsmanagement:saltstack:products:testing/salt[products:testing], is a staging flavor where new-patches that go to products are tested.
 - https://build.opensuse.org/package/show/systemsmanagement:saltstack:products:next/salt[products:next], is used for testing the major release of saltstack.

The `devel` flavor means running the tests against a local salt git repository.

[NOTE]
====
When running the upstream tests, a docker container is created first and then `py.test` is being run inside the container.

For the suse tests, the approach is different. `py.test` is being run on the host and the containers are created and used as objects in the tests.
====


== Features

 - uses containers to isolate the tests
 - possible to run the tests on different operanting systems
 - possible to run the tests in any available (OS, salt-package-version) combination
 - capable to run the tests using salt from a local git repository
 - capable of running a subset of tests
 - has ignore and xfail lists (glob-patterns) for the upstream tests (for both integration and unit tests)
 - uses tags to restrict, skip, ignore or xfail suse tests

== Setup


openSUSE system:

[source,bash]
----
sudo zypper in docker ca-certificates
----

Debian system:

[source,bash]
----
sudo zypper in docker.io ca-certificates
----

Download the registry certificate needed here: `https://gitlab.suse.de/galaxy/infrastructure/raw/master/srv/salt/ca/certs/ca.cert.pem`

Save the certificate in `/usr/share/pki/trust/anchors` (openSUSE) or in `/usr/local/share/ca-certificates/` for Debian systems

And run:
[source,bash]
----
sudo update-ca-certificates
sudo systemctl restart docker
----

==== Prerequisites:

Your systems need to have docker and docker.io pkg installed

[source,bash]
----
sudo apt in docker.io || sudo zypper in docker
----

[source,bash]
----
git clone https://github.com/openSUSE/salt-toaster.git
zypper in python-virtualenv
zypper in python2-setuptools
cd salt-toaster
virtualenv sandbox
virtualenv --relocatable sandbox
echo "*" > sandbox/.gitignore
. sandbox/bin/activate
pip install -r requirements.txt
----

== Running tests

When running tests we can choose to run:

    - the upstream integration testsuite `make saltstack.integration` 
    - the upstream unittests testsuite ` make saltstack.unit`
    - the suse testsuite `make suse.tests`

When running any of these commands, salt-toaster uses the default values for OS and salt-package version.

At the moment, the defaults are `sles12sp3` and https://build.opensuse.org/package/show/systemsmanagement:saltstack:products/salt[`saltstack:products:salt`]

The first thing that this command does is to pull the right container image from the registry(hardcoded).

With the default values the image would be: `registry.mgr.suse.de/toaster-sles12sp2-products`

== Parameters

.VERSION
Most of the time we want to run the tests against a specific OS.
We can do so by using the `VERSION` environmental variable.
 
----
make suse.tests VERSION=sles12sp3
----

.FLAVOR
The salt flavor can be specified using the `FLAVOR` environmental variable.

----
make suse.tests FLAVOR=products-testing
----

Of course, `VERSION` and `FLAVOR` can be combined

----
make suse.tests VERSION=sles12 FLAVOR=products-testing
----

.SALT_REPO
To run the tests against a local salt repository, you need to use `FLAVOR=devel` and you also need to specify the path to the salt repository with `SALT_REPO`

----
make suse.tests FLAVOR=devel SALT_REPO=/home/store/repositories/salt 
----

.SALT_TESTS
You can specify a subset of tests to run using `SALT_TESTS`

----
make suse.tests SALT_TESTS=tests/test_pkg.py
make saltstack.unit SALT_TESTS=/salt/src/salt-*/tests/unit/modules/zypper_test.py
----

.PYTEST_FLAGS
You can pass extra py.test parameters using `PYTEST_FLAGS`

----
make suse.tests SALT_TESTS=tests/test_pkg.py PYTEST_FLAGS=-x
----

.DESTRUCTIVE_TESTS
Salt tests marked as "destructive" tests are currently disabled by default. If you want to run then, simple set `DESTRUCTIVE_TESTS=True`

----
make saltstack.integration DESTRUCTIVE_TESTS=True
----

.EXPENSIVE_TESTS
Salt tests marked as "expensive" tests are currently disabled by default. If you want to run then, simple set `EXPENSIVE_TESTS=True`

----
make saltstack.integration EXPENSIVE_TESTS=True
----

[NOTE]
====
When running the `suse.tests`, `SALT_TESTS` must be a path relative to the current folder (salt-toaster)

When running the `saltstack.unit` or `saltstack.integration`, `SALT_TESTS` must be a path inside the docker container pointing to where the salt source code is extracted. Using a pattern like in the example above should always match independent of the salt-package version.
====

[cols="1,1a"]
.Available values for `VERSION` and `FLAVOR`
|===
| VERSION | rhel6, rhel7, sles11sp3, sles11sp4, sles12, sles12sp1, sles12sp2, leap42sp1
| FLAVOR  | products, products-testing, products-next, devel
|===

.DOCKER_CPUS and DOCKER_MEM

With these two parameters you can limit the resouce usage of the spun up Docker container. Examples would be `2G` or `512M` for `DOCKER_MEM` and `1` or `2.5` for `DOCKER_CPUS`. Where the number provided for `DOCKER_CPUS` would the number of host CPUs the container should able to use.

Please take a look at the official https://docs.docker.com/config/containers/resource_constraints/[Docker documentation] for more information about https://docs.docker.com/config/containers/resource_constraints/#limit-a-containers-access-to-memory[DOCKER_MEM] and https://docs.docker.com/config/containers/resource_constraints/#cpu[DOCKER_CPUS]


== Ignore/Xfail upstream tests

[source,python]
.https://github.com/openSUSE/salt-toaster/blob/documentation/conftest.py.source#L12-L289[conftest.py.source]
----
KNOWN_ISSUES_INTEGRATION = {
    'ignore_list': {
        'common': [
            'integration/files/file/base/*'  # <1>
        ],
        'products-next': [
            '*::MasterTest::test_exit_status_correct_usage'  # <2>
        ]

    },
    'xfail_list': {
        'products':[
            'integration/fileserver/roots_test.py::RootsTest::test_symlink_list'  # <3>
        ]
        'rhel6/products': [
            'integration/cli/grains.py::GrainsTargetingTest::test_grains_targeting_disconnected'  # <4>
        ]
    }
}
----
<1> ignore all upstream integration tests found in `integration/files/file/base/` on all OS and salt-package version testsuite runs
<2> ignore single test `MasterTest::test_exit_status_correct_usage` on runs using the `products-next` salt-package version
<3> xfail single test `RootsTest::test_symlink_list` on runs using the `products` salt-package version
<4> xfail single test `GrainsTargetingTest::test_grains_targeting_disconnected` on runs using `rhel6` OS and `products` salt-package version combination


== Tags

Tags can be used to identify the context in which a test runs.
NOTE: tags are only used when running `suse.tests`

Tags are set in pytest configuration files in the https://github.com/openSUSE/salt-toaster/tree/documentation/configs[./configs] folder.

Running `VERSION=sles12sp1 FLAVOR=products make suse.tests` uses the following pytest config file:

.https://github.com/openSUSE/salt-toaster/blob/documentation/configs/suse.tests/sles12sp1/products.cfg[`./configs/suse.tests/sles12sp2/products.cfg`]
----
[pytest]
addopts = --tb=short
IMAGE = registry.mgr.suse.de/toaster-sles12sp1-products
TAGS = sles sles12sp1 products
----

This means that a test can be xfailed on `sles12sp` like this:
[source,python]
----
@pytest.mark.xfailtags('sles12sp1')
def test_example():
    pass
----

It can be skipped on all test runs using the `products` salt-package version like this:
[source,python]
----
@pytest.mark.skiptags('products')
def test_example():
    pass
----

And it can be allowed to run only on `sles` like this:
[source,python]
----
@pytest.mark.tags('sles')
def test_example():
    pass
----

[NOTE]
====
In order for the `sles` tag to work as expected, it needs to be present in all config files used with sles: `./configs/suse.tests/sles*/*.cfg`

Likewise, the `products` tag would need to be present in all config files used with salt `products`: `./configs/<tests-type>/<os>/products.cfg`
====
    
Because tags are just identifiers you placed in the config files, you can create your own according to your needs. Just make sure you put them in the right config files.


== Examples

.Run docker shell in specific local image

    make docker_shell VERSION=sles12sp1 FLAVOR=products 

.Run docker shell in repository image based on version and bind rpdb port

    make docker_shell RPDB_PORT="4444" VERSION=sles12sp1 FLAVOR=products 

.Run a specific suse test using a local salt repository and sles12sp1

    make -s suse.tests VERSION=sles12sp1 FLAVOR=devel SALT_TESTS="tests/test_pkg.py::test_pkg_info_available"

.Run a subset of upstream unit tests

    make saltstack.unit VERSION=sles12sp1 FLAVOR=products SALT_TESTS=/salt/src/salt-devel/tests/unit/modules/zypper_test.py

.Run all upstream integration tests

    make saltstack.integration VERSION=sles12sp1 FLAVOR=products 


==== How to write a suse integration test

.Writing a "test.ping" test

For this we need a salt master and a minion.
We can do that by creating a new file in the `tests` folder:

.`./tests/test_example.py`
[source,python]
----
def test_ping_minion(master, minion):
    pass
----

This uses `master` and `minion` fixtures defined in `tests/conftest.py`.

NOTE: The fixtures defined in `conftest.py` (or in the current file) are automatically discovered by `py.test`

The fixtures come from https://pypi.python.org/pypi/pytest-salt-containers[pytest-salt-containers] plugin which uses https://pypi.python.org/pypi/factory_boy/[factory-boy] internally.
The factories take care of isolating the `sast-master` and `salt-minion` in separate containers.

With this, we have a running salt-master and a salt-minion.

To make master accept minion, I have created a convenient fixture called `minion_key_accepted`
Let's modify the test above to use it.

.`./tests/test_example.py`
[source,python]
----
def test_ping_minion(master, minion, minion_key_accepted):
     pass
----

To run `salt <minion-id> test.ping` on master and assert minion replied, do this:

.`./tests/test_example.py`
[source,python]
----
def test_ping_minion(master, minion, minion_key_accepted):
     assert master.salt(minion['id'], "test.ping")[minion['id']] is True
----

This might fail sometimes because the command might be run before .
In order to avoid that, I have created a `retry` helper that raises an exception if the command was not successful within `config.TIME_LIMIT`. So we need to change the test like this:

.`./tests/test_example.py`
[source,python]
----
from utils import retry


def test_ping_minion(master, minion, minion_key_accepted):

    def ping():                                                                 
        return master.salt(minion['id'], "test.ping")[minion['id']]             
                                                                               
    assert retry(ping)       
----

.Complex test requirements

When the requirements of the test are more complex, there's another way to define the containers in a single json.

[source,python]
.https://github.com/openSUSE/salt-toaster/blob/master/tests/test_saltapi.py#L4-L35[`./tests/test_saltapi.py`]
----
@pytest.fixture(scope='module')
def module_config(request):
    return {
        "masters": [  # <1>
            {
                "config": {  # <2>
                    'container__config__salt_config__sls': {  # <3>
                        'saltapi': 'tests/sls/saltapi.sls',
                    },
                    "container__config__salt_config__extra_configs": {  # <4>
                        "rosters_paths": {  # <5>
                            "rosters": ['/salt-toaster/tests/data/good.roster'],
                        },
                        "salt_api_config": {  # <6>
                            "rest_cherrypy": {
                                "port": 9080,
                                "host": "127.0.0.1",
                                "collect_stats": False,
                                "disable_ssl": True,
                            },
                            "external_auth": {  # <7>
                                "auto": {
                                    "admin": ['.*', '@wheel', '@runner', '@jobs']
                                },
                            },
                        },
                    },
                },
                "minions": [{"config": {}}]  # <8>
            }
        ]
}
----
<1> a list of dictionaries. each item in the list will generate a container and run salt-master inside
<2> configuration dictionary for the master
<3> use `container__config__salt_config__sls` to specify an sls file that will be executed during the master set-up stage
<4> use `container__config__salt_config__extra_configs` to create config files for salt in `/etc/salt/master.d` in the master container 
<5> this creates the file `/etc/salt/master.d/rosters_paths.conf` in the master container
<6> this creates the file `/etc/salt/master.d/salt_api_config.conf` in the master container
<7> this creates the file `/etc/salt/external_auth.conf` in the master container
<8> define the minions that will be controlled by this master. the minions can be defined as dictionary in the same way masters are defined as described above.


==== Running the test that we just wrote

The next thing after writing the test would probably be to run it.
We would do that with:

----
make suse.tests SALT_TESTS=tests/test_example.py::test_ping_minion`
----

This will run the test with the default `VERSION` and `FLAVOR` values but we probably wrote the test in order to implement a new salt feature or to fix some bug.
In this case we would probably want to run the test using the local checked out salt repository.
We do that with:

----
make suse.tests FLAVOR=devel SALT_REPO=/home/store/repositories/salt SALT_TESTS=tests/test_example.py::test_ping_minion
----

The test will probably fail (we didn't fix the issue yet). We can then change the salt source code and run the test again. The changes are immediatelly visible in the tests. We don't have to do anything extra, we just need to run the test again with the command above.

[NOTE]
====
When running the tests with `FLAVOR=devel`, when changing beetween salt branches we might get:

    AttributeError: 'module' object has no attribute 'BASE_THORIUM_ROOTS_DIR'

We can get over this by removing the `*.pyc` files from the salt repo using `find . -name "*.pyc" -delete`
====
