= Salt Toaster: An ultimate test suite for Salt

// settings:
:page-layout: base
:idprefix:
:idseparator: -
:source-highlighter: pygments
:source-language: python
:ext-relative: {outfilesuffix}
ifndef::env-github[]
:icons: font
++++
<link rel="stylesheet"  href="http://cdnjs.cloudflare.com/ajax/libs/font-awesome/3.1.0/css/font-awesome.min.css">
++++
endif::[]
ifdef::env-github[]
:status:
:outfilesuffix: .adoc
:caution-caption: :fire:
:important-caption: :exclamation:
:note-caption: :paperclip:
:tip-caption: :bulb:
:warning-caption: :warning:
endif::[]

image:https://api.travis-ci.org/openSUSE/salt-toaster.svg?branch=master[Build Status, link=https://travis-ci.org/openSUSE/salt-toaster]

== Description

This is a tool used to test https://github.com/saltstack/salt/[salt]

It uses pytest and containers to do so.

The tests are separated in 3 groups:

 - Saltstack upstream integration tests
 - Saltstack upstream unit tests
 - SUSE custom integration tests

There are 3 predefined flavors of Salt packages plus a `devel` flavor.
The predefined flavors are packages served from OBS:

 - https://build.opensuse.org/package/show/systemsmanagement:saltstack:products/salt[products], the flavor for released packages
 - https://build.opensuse.org/package/show/systemsmanagement:saltstack:products:testing/salt[products:testing], is a staging flavor where new-patches that go to products are tested.
 - https://build.opensuse.org/package/show/systemsmanagement:saltstack:products:next/salt[products:next], is used for testing the major release of saltstack.

The `devel` flavor means running the tests against a local Salt git repository.

[NOTE]
====
When running the upstream tests, a docker container is created first and then `py.test` is being run inside the container.

For the suse tests, the approach is different. `py.test` is being run on the host and the containers are created and used as objects in the tests.
====


== Features

 - Uses containers to isolate the tests
 - Possible to run the tests on different operanting systems
 - Possible to run the tests in any available (OS, salt-package-version) combination
 - Capable to run the tests using salt from a local git repository
 - Capable of running a subset of tests
 - Has ignore and xfail lists (glob-patterns) for the upstream tests (for both integration and unit tests)
 - Uses tags to restrict, skip, ignore or xfail suse tests


== How to run Salt Toaster

=== Prerequisites:

openSUSE system:

[source,bash]
----
sudo zypper in docker python python-virtualenv make
----

Debian system:
Your systems need to have docker and docker.io pkg installed

[source,bash]
----
sudo apt install docker.io || sudo apt install docker
----

If you are part of the SUSE R&D network, you can access the non-public images. Please read the instructions here link:README_SUSE{ext-relative}[SUSE internal only].

=== Preparing the sandbox:

[source,bash]
----
git clone https://github.com/openSUSE/salt-toaster.git
cd salt-toaster
virtualenv sandbox
. sandbox/bin/activate
pip install -r requirements.txt
----

=== Show help:

[source,bash]
----
make help
----

=== List available targets:

In order to list the what targets (VERSION and FLAVOR) are available for testing:

[source,bash]
----
make list_targets
----

=== Running the tests

When running tests we can choose to run:

    - Saltstack upstream integration testsuite `make saltstack.integration`
    - Saltstack upstream unit testsuite `make saltstack.unit`
    - SUSE custom testsuite `make suse.tests`

When running any of these commands, salt-toaster uses the default values for OS and salt-package version.

At the moment, the default VERSION is `opensuse151` and FLAVOR is `devel`

The first step this command will perform is to pull the right container image from the respective Docker registry.

=== Parameters

.VERSION
Most of the time we want to run the tests against a specific OS.
We can do so by using the `VERSION` environmental variable.

----
make suse.tests VERSION=opensuse151
----

.FLAVOR
The salt flavor can be specified using the `FLAVOR` environmental variable.

----
make suse.tests FLAVOR=products-testing
----

Of course, `VERSION` and `FLAVOR` can be combined

----
make suse.tests VERSION=sles15 FLAVOR=products-testing
----

.SALT_REPO
To run the tests against a local salt repository, you need to use `FLAVOR=devel` and you also need to specify the path to the salt repository with `SALT_REPO`

----
make suse.tests FLAVOR=devel SALT_REPO=/home/store/repositories/salt
----

.SALT_TESTS
You can specify a subset of tests to run using `SALT_TESTS`

----
make suse.tests SALT_TESTS=tests/test_pkg.py
make saltstack.unit SALT_TESTS=/salt/src/salt-*/tests/unit/modules/zypper_test.py
----

.PYTEST_FLAGS
You can pass extra py.test parameters using `PYTEST_FLAGS`

----
make suse.tests SALT_TESTS=tests/test_pkg.py PYTEST_FLAGS=-x
----

.DESTRUCTIVE_TESTS
Salt tests marked as "destructive" tests are currently disabled by default. If you want to run then, simple set `DESTRUCTIVE_TESTS=True`

----
make saltstack.integration DESTRUCTIVE_TESTS=True
----

.EXPENSIVE_TESTS
Salt tests marked as "expensive" tests are currently disabled by default. If you want to run then, simple set `EXPENSIVE_TESTS=True`

----
make saltstack.integration EXPENSIVE_TESTS=True
----

[NOTE]
====
When running the `suse.tests`, `SALT_TESTS` must be a path relative to the current folder (salt-toaster)

When running the `saltstack.unit` or `saltstack.integration`, `SALT_TESTS` must be a path inside the docker container pointing to where the salt source code is extracted. Using a pattern like in the example above should always match independent of the salt-package version.
====

[cols="1,1a"]
.Available public targets (`VERSION` and `FLAVOR`):
|===
| VERSION | opensuse423, opensuse150, opensuse151, tumbleweed, centos7, ubuntu1604, ubuntu1804
| FLAVOR  | devel
|===

.Available SUSE private (R&D network only) targets (`VERSION` and `FLAVOR`):
|===
| VERSION | rhel6, rhel7, sles11sp3, sles11sp4, sles12, sles12sp1, sles12sp3, sles15, sles15sp1
| FLAVOR  | products, products-testing, products-next, devel
|===

.DOCKER_CPUS and DOCKER_MEM

With these two parameters you can limit the resouce usage of the spun up Docker container. Examples would be `2G` or `512M` for `DOCKER_MEM` and `1` or `2.5` for `DOCKER_CPUS`. Where the number provided for `DOCKER_CPUS` would the number of host CPUs the container should able to use.

Please take a look at the official https://docs.docker.com/config/containers/resource_constraints/[Docker documentation] for more information about https://docs.docker.com/config/containers/resource_constraints/#limit-a-containers-access-to-memory[DOCKER_MEM] and https://docs.docker.com/config/containers/resource_constraints/#cpu[DOCKER_CPUS]

== Examples

.Run docker shell in specific local image

    make docker_shell VERSION=sles12sp1 FLAVOR=products

.Run docker shell in repository image based on version and bind rpdb port

    make docker_shell RPDB_PORT="4444" VERSION=sles12sp1 FLAVOR=products

.Run a specific suse test using a local salt repository and sles12sp1

    make -s suse.tests VERSION=sles12sp1 FLAVOR=devel SALT_TESTS="tests/test_pkg.py::test_pkg_info_available"

.Run a subset of upstream unit tests

    make saltstack.unit VERSION=sles12sp1 FLAVOR=products SALT_TESTS=/salt/src/salt-devel/tests/unit/modules/zypper_test.py

.Run all upstream integration tests

    make saltstack.integration VERSION=sles12sp1 FLAVOR=products

== Advanced Usage:

Please read the link:README_ADVANCED{ext-relative}[ADVANCED README]

== Demo:

++++
<a href="https://asciinema.org/a/ueg4BkJ96Nf6ewoq5QXaavpPa" target="_blank"><img src="https://asciinema.org/a/ueg4BkJ96Nf6ewoq5QXaavpPa.svg" /></a>
++++
