GRAINS_EXPECTATIONS = {
    'ubuntu1604': {
        'os': 'Ubuntu',
        'oscodename': 'xenial',
        'os_family': 'Debian',
        'osfullname': 'Ubuntu',
        'osarch': 'amd64',
        'osrelease': '16.04',
        'osrelease_info': [16, 4],
    },
    'ubuntu1804': {
        'os': 'Ubuntu',
        'oscodename': 'bionic',
        'os_family': 'Debian',
        'osfullname': 'Ubuntu',
        'osarch': 'amd64',
        'osrelease': '18.04',
        'osrelease_info': [18, 4],
    },
    'rhel6': {
        'os': 'RedHat',
        'oscodename': 'Santiago',
        'os_family': 'RedHat',
        'osfullname': 'Red Hat Enterprise Linux Server',
        'osrelease': '6.8',
        'osrelease_info': [6, 8],
    },
    'rhel7': {
        'os': 'RedHat',
        'oscodename': 'Maipo',
        'os_family': 'RedHat',
        'osfullname': 'Red Hat Enterprise Linux Server',
        'osrelease': '7.2',
        'osrelease_info': [7, 2],
    },
    'rhel8': {
        'os': 'RedHat',
        'oscodename': 'Ootpa',
        'os_family': 'RedHat',
        'osfullname': 'Red Hat Enterprise Linux',
        'osrelease': '8.1',
        'osrelease_info': [8, 1],
    },
    'sles11sp3': {
        'os': 'SUSE',
        'oscodename': 'SUSE Linux Enterprise Server 11 SP3',
        'os_family': 'Suse',
        'osfullname': 'SLES',
        'osrelease': '11.3',
        'osrelease_info': [11, 3],
    },
    'sles11sp4': {
        'os': 'SUSE',
        'oscodename': 'SUSE Linux Enterprise Server 11 SP4',
        'os_family': 'Suse',
        'osfullname': 'SLES',
        'osrelease': '11.4',
        'osrelease_info': [11, 4],
    },
    'sles12': {
        'os': 'SUSE',
        'oscodename': 'SUSE Linux Enterprise Server 12',
        'os_family': 'Suse',
        'osfullname': 'SLES',
        'osrelease': '12',
        'osrelease_info': [12],
    },
    'sles12sp1': {
        'os': 'SUSE',
        'oscodename': 'SUSE Linux Enterprise Server 12 SP1',
        'os_family': 'Suse',
        'osfullname': 'SLES',
        'osrelease': '12.1',
        'osrelease_info': [12, 1],
    },
    'sles12sp2': {
        'os': 'SUSE',
        'oscodename': 'SUSE Linux Enterprise Server 12 SP2',
        'os_family': 'Suse',
        'osfullname': 'SLES',
        'osrelease': '12.2',
        'osrelease_info': [12, 2],
    },
    'sles12sp3': {
        'os': 'SUSE',
        'oscodename': 'SUSE Linux Enterprise Server 12 SP3',
        'os_family': 'Suse',
        'osfullname': 'SLES',
        'osrelease': '12.3',
        'osrelease_info': [12, 3],
    },
    'sles15': {
        'os': 'SUSE',
        'oscodename': 'SUSE Linux Enterprise Server 15',
        'os_family': 'Suse',
        'osfullname': 'SLES',
        'osrelease': '15',
        'osrelease_info': [15],
    },
    'sles15sp1': {
        'os': 'SUSE',
        'oscodename': 'SUSE Linux Enterprise Server 15 SP1',
        'os_family': 'Suse',
        'osfullname': 'SLES',
        'osrelease': '15.1',
        'osrelease_info': [15, 1],
    },
    'sles15sp2': {
        'os': 'SUSE',
        'oscodename': 'SUSE Linux Enterprise Server 15 SP2',
        'os_family': 'Suse',
        'osfullname': 'SLES',
        'osrelease': '15.2',
        'osrelease_info': [15, 2],
    },
    'opensuse423': {
        'os': 'SUSE',
        'oscodename': 'openSUSE Leap 42.3',
        'os_family': 'Suse',
        'osfullname': 'Leap',
        'osrelease': '42.3',
        'osrelease_info': [42, 3],
    },
    'opensuse150': {
        'os': 'SUSE',
        'oscodename': 'openSUSE Leap 15.0',
        'os_family': 'Suse',
        'osfullname': 'Leap',
        'osrelease': '15.0',
        'osrelease_info': [15, 0],
    },
    'opensuse151': {
        'os': 'SUSE',
        'oscodename': 'openSUSE Leap 15.1',
        'os_family': 'Suse',
        'osfullname': 'Leap',
        'osrelease': '15.1',
        'osrelease_info': [15, 1],
    },
    'tumbleweed': {
        'os': 'SUSE',
        'oscodename': 'openSUSE Tumbleweed',
        'os_family': 'Suse',
        'osfullname': 'Tumbleweed',
        'osrelease': None, # This grain changes on each snapshot
        'osrelease_info': None, # This grain changes on each snapshot
    },
    'leap42sp1': {
        'os': 'openSUSE Leap',
        'oscodename': 'openSUSE Leap 42.1 (x86_64)',
        'os_family': 'Suse',
        'osfullname': 'openSUSE Leap',
        'osrelease': '42.1',
        'osrelease_info': [42, 1],
    },
    'centos7': {
        'os': 'CentOS',
        'oscodename': 'CentOS Linux 7 (Core)',
        'os_family': 'RedHat',
        'osfullname': 'CentOS Linux',
        'osrelease': '7.6.1810',
        'osrelease_info': [7, 6, 1810],
    },
}
