GRAINS_EXPECTATIONS = {
    'rhel6': {
        'os': 'RedHat',
        'oscodename': 'Santiago',
        'os_family': 'RedHat',
        'osfullname': 'Red Hat Enterprise Linux Server',
        'osrelease': '6.8',
        'osrelease_info': [6, 8],
    },
    'rhel7': {
        'os': 'RedHat',
        'oscodename': 'Maipo',
        'os_family': 'RedHat',
        'osfullname': 'Red Hat Enterprise Linux Server',
        'osrelease': '7.2',
        'osrelease_info': [7, 2],
    },
    'sles11sp3': {
        'os': 'SUSE',
        'oscodename': 'SUSE Linux Enterprise Server 11 SP3',
        'os_family': 'Suse',
        'osfullname': 'SLES',
        'osrelease': '11.3',
        'osrelease_info': [11, 3],
    },
    'sles11sp4': {
        'os': 'SUSE',
        'oscodename': 'SUSE Linux Enterprise Server 11 SP4',
        'os_family': 'Suse',
        'osfullname': 'SLES',
        'osrelease': '11.4',
        'osrelease_info': [11, 4],
    },
    'sles12': {
        'os': 'SUSE',
        'oscodename': 'SUSE Linux Enterprise Server 12',
        'os_family': 'Suse',
        'osfullname': 'SLES',
        'osrelease': '12',
        'osrelease_info': [12],
    },
    'sles12sp1': {
        'os': 'SUSE',
        'oscodename': 'SUSE Linux Enterprise Server 12 SP1',
        'os_family': 'Suse',
        'osfullname': 'SLES',
        'osrelease': '12.1',
        'osrelease_info': [12, 1],
    },
    'sles12sp2': {
        'os': 'SUSE',
        'oscodename': 'SUSE Linux Enterprise Server 12 SP2',
        'os_family': 'Suse',
        'osfullname': 'SLES',
        'osrelease': '12.2',
        'osrelease_info': [12, 2],
    },
    'sles12sp3': {
        'os': 'SUSE',
        'oscodename': 'SUSE Linux Enterprise Server 12 SP3',
        'os_family': 'Suse',
        'osfullname': 'SLES',
        'osrelease': '12.3',
        'osrelease_info': [12, 3],
    },
    'sles15': {
        'os': 'SUSE',
        'oscodename': 'SUSE Linux Enterprise Server 15',
        'os_family': 'Suse',
        'osfullname': 'SLES',
        'osrelease': '15',
        'osrelease_info': [15],
    },
    'leap15': {
        'os': 'openSUSE Leap',
        'oscodename': 'openSUSE Leap 15 (x86_64)',
        'os_family': 'Suse',
        'osfullname': 'openSUSE Leap',
        'osrelease': '15',
        'osrelease_info': [15],
    }
}
