# Container used to run salt tests focusing on SUSE Manager use cases
#
# NAME                  toaster-sles12sp1-devel
# VERSION               0
FROM registry.mgr.suse.de/toaster-sles12sp1-products
MAINTAINER Mihai Dinca: "mdinca@suse.com"

RUN zypper --non-interactive rm salt
RUN /root/bin/prepare_devel.sh
ADD docker/salt.archive /salt/src/salt-devel
RUN pip install -e /salt/src/salt-devel
