# Container used to run salt tests focusing on SUSE Manager use cases
#
# NAME                  toaster-sles11sp4-testing
# VERSION               0

FROM registry.mgr.suse.de/suma-3.0-salt-sle11sp4
MAINTAINER Mihai Dinca: "mdinca@suse.com"


COPY bin/ /root/bin/

# Use your credentials for the 'nu.novell' domain within the URL, in case required
RUN zypper ar -f http://download.opensuse.org/repositories/systemsmanagement:/saltstack:/testing/SLE_11_SP4/ "salt"
RUN zypper mr -p 1 salt

RUN /root/bin/add_packages.sh
RUN /root/bin/install_salt.sh
