# Container used to run salt tests focusing on SUSE Manager use cases
#
# NAME                  toaster-sles12-products
# VERSION               0

FROM registry.mgr.suse.de/suma-3.0-salt-sle12
MAINTAINER Mihai Dincă: "mdinca@suse.com"


ADD . /root

RUN /root/sles12/products/add_repositories.sh
RUN /root/sles12/products/add_packages.sh
RUN /root/bin/install_salt.sh
