# Container used to run salt tests focusing on SUSE Manager use cases
#
# NAME                  toaster-rhel7-devel
# VERSION               0
FROM registry.mgr.suse.de/toaster-rhel7-products
MAINTAINER Mihai Dinca: "mdinca@suse.com"

COPY bin/patch.sh /root/bin
ADD patches/ /salt/src/

RUN zypper --non-interactive rm salt
RUN /root/bin/prepare_devel.sh

ADD salt.archive /salt/src/salt-devel
RUN /root/bin/patch.sh
RUN pip install -e /salt/src/salt-devel

RUN mkdir -p /etc/salt
