# Container used to run salt tests focusing on SUSE Manager use cases
#
# NAME                  toaster-leap42sp1-devel
# VERSION               0
FROM registry.mgr.suse.de/toaster-leap42sp1-default
MAINTAINER Mihai Dinca: "mdinca@suse.com"

COPY bin/prepare_devel.sh /root/bin

RUN zypper --non-interactive rm salt
RUN /root/bin/prepare_devel.sh

ADD salt.archive /salt/src/salt-devel
RUN pip install -e /salt/src/salt-devel
