# Container used to run salt tests focusing on SUSE Manager use cases
#
# NAME                  toaster-sles11sp4-testing
# VERSION               0

FROM registry.mgr.suse.de/suma-3.0-salt-sle11sp4
MAINTAINER Mihai Dincă: "mdinca@suse.com"


ADD . /root

RUN /root/sles11sp4/testing/add_repositories.sh
RUN /root/bin/add_packages.sh
RUN /root/bin/install_salt.sh
