# Container used to run salt tests focusing on SUSE Manager use cases
#
# NAME                  toaster-leap42sp1-testing
# VERSION               0
FROM opensuse:42.1
MAINTAINER Mihai Dinca: "mdinca@suse.com"

COPY bin/add_packages.sh /root/bin/add_packages.sh
COPY bin/unpack_salt.sh /root/bin/unpack_salt.sh
COPY bin/install_salt.sh /root/bin/install_salt.sh
COPY bin/lastchangelog /root/bin/lastchangelog
COPY Makefile /root/Makefile

RUN zypper ar -f http://download.opensuse.org/repositories/systemsmanagement:/saltstack:/testing:/testpackages/SLE_12/ "testpackages"
RUN zypper ar -f http://download.opensuse.org/repositories/systemsmanagement:/saltstack:/testing/SLE_12_SP1/ "salt"
RUN zypper mr -p 1 salt

RUN zypper --non-interactive --gpg-auto-import-keys ref
RUN zypper -n in rpm-build

RUN /root/bin/add_packages.sh
RUN /root/bin/install_salt.sh

ENTRYPOINT ["make", "-f", "/root/Makefile", "-C", "/salt-toaster"]
CMD ["default"]
