# Container used to run salt tests focusing on SUSE Manager use cases
#
# NAME                  toaster-rhel7-products-3000-testing
# VERSION               0



# list rhel7 tags
# curl -L https://registry.hub.docker.com/v1/repositories/rhel7/tags --http1.0 | python -m json.tool
FROM registry.mgr.suse.de/rhel7:7.2-104
MAINTAINER Mihai Dinca: "mdinca@suse.com"


ENV LC_ALL en_US.UTF-8
COPY Makefile /root/Makefile
COPY get-pip.py /root/get-pip.py
COPY wheels/ /root/wheels/
COPY docker-requirements.txt /root/
COPY docker-requirements-rhel8.txt /root/
COPY docker-requirements-common.txt /root/
COPY py26-docker-requirements.txt /root/
COPY bin/lastchangelog /root/bin/lastchangelog

ARG CACHE_DATE=nocache

RUN rpm -e subscription-manager


####### Install missing dependencies from centos7 ########
RUN yum-config-manager --add-repo http://ftp.fau.de/centos/7/os/x86_64/
RUN yum-config-manager --add-repo http://ftp.fau.de/centos/7/updates/x86_64/
RUN yum-config-manager --add-repo http://ftp.fau.de/centos/7/extras/x86_64/

RUN rpm --import http://ftp.fau.de/centos/7/os/x86_64/RPM-GPG-KEY-CentOS-7





RUN yum-config-manager --add-repo http://download.opensuse.org/repositories/systemsmanagement:/saltstack:/testing:/testpackages/RHEL_7/
RUN rpm --import http://download.opensuse.org/repositories/systemsmanagement:/saltstack:/testing:/testpackages/RHEL_7/repodata/repomd.xml.key

RUN yum-config-manager --add-repo http://download.opensuse.org/repositories/systemsmanagement:/saltstack:/products:/3000:/testing/CentOS_7/

RUN rpm --import http://download.opensuse.org/repositories/systemsmanagement:/saltstack:/products:/3000:/testing/CentOS_7//repodata/repomd.xml.key
RUN yum -y --nogpgcheck install python python-devel



RUN python /root/get-pip.py --no-index /root/wheels/pip-9.0.3-py2.py3-none-any.whl /root/wheels/setuptools-33.1.1-py2.py3-none-any.whl -f /root/wheels/



RUN yum -y --nogpgcheck clean all
RUN yum -y --nogpgcheck install which make gcc-c++ rpm-build quilt tar iproute bind-utils net-tools

RUN yum -y --nogpgcheck install test-package

RUN yum -y --nogpgcheck install openssh-clients openssh-server nc tzdata python-urllib3 vim vim-data

RUN pip install --no-index -f /root/wheels/ -r /root/docker-requirements.txt


RUN rpm -e --quiet python-salt-testing || true
RUN pip uninstall -y salttesting || true
RUN yum -y --nogpgcheck install git
RUN pip install -U --no-deps git+https://github.com/saltstack/salt-testing.git
RUN yum -y --nogpgcheck install salt-master salt-minion salt-proxy salt-ssh python-markupsafe


# RUN yum -y --nogpgcheck install oscap openscap-content



# RUN pip install moto

RUN pip install --no-index --upgrade --force -f /root/wheels /root/wheels/psutil-5.4.5.tar.gz  # overwrite old psutil using pip
RUN pip install --no-index --force -f /root/wheels /root/wheels/saltrepoinspect-1.0.tar.gz

RUN pip install --no-index --force -f /root/wheels pytest-catchlog --ignore-installed six



RUN pip --trusted-host pypi.python.org install rsa==3.4.2

RUN pip --trusted-host pypi.python.org install pytest==4.6.5 pytest-helpers-namespace pytest-timeout mock timelib boto kubernetes==2.0.0 apache-libcloud unittest2 pytest-salt==2019.12.7 gitpython




ENTRYPOINT ["make", "-f", "/root/Makefile", "-C", "/salt-toaster"]
CMD ["default"]
