# Container used to run salt tests focusing on SUSE Manager use cases
#
# NAME                  toaster-rhel8-products-2019.2.0-testing
# VERSION               0



FROM registry.mgr.suse.de/rhel8:latest
MAINTAINER Pablo Suarez Hernandez: "psuarezhernandez@suse.com"



ENV LC_ALL en_US.UTF-8
COPY Makefile /root/Makefile
COPY get-pip.py /root/get-pip.py
COPY wheels/ /root/wheels/
COPY docker-requirements.txt /root/
COPY docker-requirements-rhel8.txt /root/
COPY docker-requirements-common.txt /root/
COPY py26-docker-requirements.txt /root/
COPY bin/lastchangelog /root/bin/lastchangelog

ARG CACHE_DATE=nocache

RUN rpm -e subscription-manager


####### Install missing dependencies from centos8 ########

RUN dnf config-manager --add-repo http://ftp.fau.de/centos/8/BaseOS/x86_64/os/
RUN dnf config-manager --add-repo http://ftp.fau.de/centos/8/AppStream/x86_64/os/
RUN dnf config-manager --add-repo http://ftp.fau.de/centos/8/extras/x86_64/os/


RUN dnf config-manager --add-repo http://download.opensuse.org/repositories/systemsmanagement:/saltstack:/testing:/testpackages/CentOS_8/
RUN rpm --import http://download.opensuse.org/repositories/systemsmanagement:/saltstack:/testing:/testpackages/CentOS_8/repodata/repomd.xml.key
RUN dnf config-manager --add-repo http://download.opensuse.org/repositories/systemsmanagement:/saltstack:/products:/testing:/res8-dependencies/CentOS_8/
RUN rpm --import http://download.opensuse.org/repositories/systemsmanagement:/saltstack:/products:/testing:/res8-dependencies/CentOS_8/repodata/repomd.xml.key

RUN dnf config-manager --add-repo http://download.opensuse.org/repositories/systemsmanagement:/saltstack:/products:/2019.2.0:/testing/CentOS_8/
RUN rpm --import http://download.opensuse.org/repositories/systemsmanagement:/saltstack:/products:/2019.2.0:/testing/CentOS_8//repodata/repomd.xml.key

RUN dnf -y --nogpgcheck install python36 python36-devel


RUN /usr/libexec/platform-python /root/get-pip.py --no-index /root/wheels/pip-9.0.3-py2.py3-none-any.whl /root/wheels/setuptools-33.1.1-py2.py3-none-any.whl -f /root/wheels/



RUN dnf -y --nogpgcheck clean all

RUN dnf -y --nogpgcheck install which make gcc-c++ rpm-build tar iproute bind-utils net-tools
RUN dnf -y --nogpgcheck install test-package


RUN dnf -y --nogpgcheck install openssh-clients nc tzdata vim glibc-langpack-en
RUN localedef -i en_US -f UTF-8 en_US.UTF-8 | true

RUN pip install --no-index -f /root/wheels/ -r /root/docker-requirements-rhel8.txt

RUN rpm -e --quiet python-salt-testing || true
RUN pip uninstall -y salttesting || true
RUN dnf -y --nogpgcheck install git
RUN pip install -U --no-deps git+https://github.com/saltstack/salt-testing.git

RUN dnf -y --nogpgcheck install salt-master salt-minion salt-proxy salt-ssh

# RUN dnf -y --nogpgcheck install oscap openscap-content



# RUN pip install moto

RUN pip install --no-index --upgrade --force -f /root/wheels /root/wheels/psutil-5.4.5.tar.gz  # overwrite old psutil using pip
RUN pip install --no-index --force -f /root/wheels /root/wheels/saltrepoinspect-1.0.tar.gz



RUN pip --trusted-host pypi.python.org install --upgrade pytest==4.6.5 pytest-helpers-namespace pytest-timeout mock timelib boto kubernetes==2.0.0 apache-libcloud unittest2 pytest-salt==2019.12.7 gitpython


ENTRYPOINT ["make", "-f", "/root/Makefile", "-C", "/salt-toaster"]
CMD ["default"]
