# Container used to run salt tests focusing on SUSE Manager use cases
#
# NAME                  toaster-sles15-products-2019.2.0-testing
# VERSION               0



FROM registry.mgr.suse.de/sles15
MAINTAINER Mihai Dinca: "mdinca@suse.com"


ENV LC_ALL en_US.UTF-8
COPY Makefile /root/Makefile
COPY get-pip.py /root/get-pip.py
COPY wheels/ /root/wheels/
COPY docker-requirements.txt /root/
COPY docker-requirements-rhel8.txt /root/
COPY docker-requirements-common.txt /root/
COPY py26-docker-requirements.txt /root/
COPY bin/lastchangelog /root/bin/lastchangelog


COPY bin/install_salt.sh /root/bin/install_salt.sh
ARG CACHE_DATE=nocache
COPY vendors.conf /etc/zypp/vendors.d/vendors.conf
RUN zypper ar -f http://download.suse.de/ibs/SUSE:/SLE-15:/GA/standard/ "sles15ga"

RUN zypper -n ar -f http://download.opensuse.org/repositories/systemsmanagement:/saltstack:/testing:/testpackages/SLE_15/ "testpackages"

RUN zypper ar -f http://download.opensuse.org/repositories/systemsmanagement:/saltstack:/products:/2019.2.0:/testing/SLE_15/ "salt"
RUN zypper mr -p 1 salt

RUN zypper --non-interactive --gpg-auto-import-keys ref
RUN zypper -nq in curl vim vim-data
RUN zypper -n in --no-recommends python python-devel python-xml
RUN zypper -n in --no-recommends python3 python3-devel python3-xml


RUN python3 /root/get-pip.py --no-index /root/wheels/pip-9.0.3-py2.py3-none-any.whl /root/wheels/setuptools-33.1.1-py2.py3-none-any.whl -f /root/wheels/


RUN zypper --non-interactive --gpg-auto-import-keys ref
RUN zypper -n in python3-xml python3-pip python3-CherryPy
RUN zypper -n in --no-recommends python3-devel make bind-utils gcc-c++ openssh rsync
RUN zypper -n in -y --force-resolution patch rpmbuild
RUN useradd -ms /bin/bash nobody



RUN /root/bin/install_salt.sh

RUN zypper -n rm container-suseconnect
RUN zypper -n in netcat-openbsd timezone # spacewalk-oscap openscap-content vim vim-data
RUN pip install -U --no-deps --no-index -f /root/wheels /root/wheels/salt-testing-2018.1.16.tar.gz


RUN zypper -n in python3-pyOpenSSL



# RUN pip install moto

RUN pip install --no-index --upgrade --force -f /root/wheels /root/wheels/psutil-5.4.5.tar.gz  # overwrite old psutil using pip
RUN pip install --no-index --force -f /root/wheels /root/wheels/saltrepoinspect-1.0.tar.gz

RUN pip install --no-index --force -f /root/wheels pytest-catchlog --ignore-installed six




RUN pip --trusted-host pypi.python.org install --upgrade pytest==4.6.5 pytest-helpers-namespace pytest-timeout mock timelib boto kubernetes==2.0.0 apache-libcloud unittest2 pytest-salt==2019.12.7 gitpython


RUN pip install --upgrade pip

ENTRYPOINT ["make", "-f", "/root/Makefile", "-C", "/salt-toaster"]
CMD ["default"]
