# Container used to run salt tests focusing on SUSE Manager use cases
#
# NAME                  toaster-sles12-products-testing
# VERSION               0



FROM registry.mgr.suse.de/sles12
MAINTAINER Mihai Dinca: "mdinca@suse.com"

COPY bin/install_salt.sh /root/bin/install_salt.sh
COPY bin/lastchangelog /root/bin/lastchangelog
COPY Makefile /root/Makefile
COPY get-pip.py /root/get-pip.py

# Use your credentials for the 'nu.novell' domain within the URL, in case required
RUN zypper ar -f http://nu.novell.com/SUSE/Products/SLE-SERVER/12/x86_64/product/ "SLES 12 Pool"
RUN zypper ar -f http://nu.novell.com/SUSE/Updates/SLE-SERVER/12/x86_64/update/ "SLES 12 Updates"
RUN zypper ar -f http://nu.novell.com/SUSE/Products/SLE-SDK/12/x86_64/product/ "SLE-SDK 12 Pool"
RUN zypper ar -f http://nu.novell.com/SUSE/Updates/SLE-SDK/12/x86_64/update/ "SLE-SDK 12 Updates"
RUN zypper ar -f http://nu.novell.com/SUSE/Products/SLE-Module-Public-Cloud/12/x86_64/product/ "SLE-Module-Public-Cloud 12 Pool"
RUN zypper ar -f http://nu.novell.com/SUSE/Updates/SLE-Module-Public-Cloud/12/x86_64/update/ "SLE-Module-Public-Cloud 12 Updates"
RUN zypper ar -f http://nu.novell.com/SUSE/Products/SLE-Manager-Tools/12/x86_64/product/ "SLE-Manager-Tools 12 Pool"
RUN zypper ar -f http://nu.novell.com/SUSE/Updates/SLE-Manager-Tools/12/x86_64/update/ "SLE-Manager-Tools 12 Updates"

RUN zypper ar -f http://download.opensuse.org/repositories/systemsmanagement:/saltstack:/testing:/testpackages/SLE_12/ "testpackages"
ARG CACHE_DATE=nocache

RUN zypper ar -f http://ftp.gwdg.de/pub/opensuse/repositories/systemsmanagement:/saltstack:/products:/testing/SLE_12/ "salt"
RUN zypper mr -p 1 salt
RUN zypper ar -f http://download.opensuse.org/repositories/devel:/languages:/python/SLE_12/devel:languages:python.repo
RUN zypper mr -p 99 devel_languages_python

RUN zypper --non-interactive --gpg-auto-import-keys ref
RUN zypper -n in rpm-build

# make sure the package repository is up to date
RUN zypper --non-interactive --gpg-auto-import-keys ref
RUN zypper -n in --no-recommends python-devel make bind-utils gcc-c++ openssh rsync

RUN zypper -n in --no-recommends python-pip # python-apache-libcloud

RUN pip install --upgrade pip
RUN pip --trusted-host pypi.python.org install pytest==3.1.1 pytest-timeout mock==1.0.0 timelib boto six kubernetes==2.0.0 apache-libcloud pyyaml==3.11 unittest2


RUN pip install -U setuptools

RUN /root/bin/install_salt.sh

RUN zypper -n in netcat-openbsd timezone # spacewalk-oscap openscap-content
RUN pip install -U --no-deps git+https://github.com/saltstack/salt-testing.git


# RUN pip install moto
RUN pip install --upgrade psutil  # overwrite old psutil using pip
RUN pip install git+https://github.com/dincamihai/saltrepoinspect.git
ENTRYPOINT ["make", "-f", "/root/Makefile", "-C", "/salt-toaster"]
CMD ["default"]
